.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. nationalbitcoin_qt test_nationalbitcoin_qt
clean: FORCE
	$(MAKE) -C .. nationalbitcoin_qt_clean test_nationalbitcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_nationalbitcoin_qt_check
nationalbitcoin-qt nationalbitcoin-qt.exe: FORCE
	 $(MAKE) -C .. nationalbitcoin_qt
